#!/bin/bash

if [ "$#" != "1" ]; then
  echo "Usage:" $0 "<input file name>"
  exit 1
fi

INPUT=$1
OUTPUT=$INPUT.out

sbt 'apps/runMain org.clulab.processors.apps.CommandLineInterface -input '"$INPUT"' -output '"$OUTPUT"
