#!/bin/sh

#
# constructs the model jar using the naming convention expected by maven
#

if [ "$#" != "1" ]; then
  echo "Usage: $0 <release.number>"
  exit 1
fi

RNUM=$1
cp target/classes/nivreeager-en-crammer.mco target/processors-$RNUM-models.jar
