#!/bin/sh

#
# constructs the model jar using the naming convention expected by maven
#

if [ "$#" != "1" ]; then
  echo "Usage: $0 <release.number>"
  exit 1
fi

RNUM=$1
WDIR=target/model_tmp

mkdir -p $WDIR

# RST resources
mkdir -p $WDIR/edu/arizona/sista/discourse
cp -r target/test-classes/edu/arizona/sista/discourse/rstparser $WDIR/edu/arizona/sista/discourse/

# maltparser resources
cd $WDIR
tar xvf ../test-classes/nivreeager-en-crammer.mco

# create the actual model jar file
jar cvf ../processors-$RNUM-models.jar *

# and remove the temporary working dir
cd ../..
rm -rf $WDIR

