#!/bin/sh

#
# Runs processors classes in the command line (assumes the code is in ~/github/processors)
# Adds all necessary dependencies to the $CLASSPATH, including processors/target/classes
#

PROCESSORS_HOME=$HOME/github/processors
M2=$HOME/.m2/repository
HEAP=6g
VER=3.0

PROCESSORS_CLASSES=$PROCESSORS_HOME/target/classes:$PROCESSORS_HOME/target/test-classes
#PROCESSORS_CLASSES=$PROCESSORS_HOME/target/processors-$VER.jar:$PROCESSORS_HOME/target/processors-$VER-models.jar

export CLASSPATH=.:$PROCESSORS_CLASSES:$M2/edu/stanford/nlp/stanford-corenlp/3.3.1/stanford-corenlp-3.3.1.jar:$M2/edu/stanford/nlp/stanford-corenlp/3.3.1/stanford-corenlp-3.3.1-models.jar:$M2/ch/qos/logback/logback-classic/1.0.10/logback-classic-1.0.10.jar:$M2/ch/qos/logback/logback-core/1.0.10/logback-core-1.0.10.jar:$M2/org/slf4j/slf4j-api/1.7.3/slf4j-api-1.7.3.jar:$M2/org/apache/lucene/lucene-core/3.0.3/lucene-core-3.0.3.jar:$M2/mysql/mysql-connector-java/5.1.13/mysql-connector-java-5.1.13.jar:$M2/junit/junit/4.10/junit-4.10.jar:$M2/xom/xom/1.2.5/xom-1.2.5.jar:$M2/postgresql/postgresql/9.0-801.jdbc4/postgresql-9.0-801.jdbc4.jar:$M2/joda-time/joda-time/2.1/joda-time-2.1.jar:$M2/de/jollyday/jollyday/0.4.7/jollyday-0.4.7.jar:$M2/de/bwaldvogel/liblinear/1.94/liblinear-1.94.jar:$M2/log4j/log4j/1.2.17/log4j-1.2.17.jar:tw/edu/ntu/csie/libsvm/3.17/libsvm-3.17.jar:$M2/junit/junit/4.10/junit-4.10.jar:$M2/org/scalatest/scalatest_2.10/2.0.M6-SNAP17/scalatest_2.10-2.0.M6-SNAP17.jar

time env JAVA_OPTS="-Xmx$HEAP -XX:MaxPermSize=512m -enableassertions" scala -classpath $CLASSPATH $@

